export const LOAD_CHILDREN = 'App/LOAD_CHILDREN';
export const LOAD_CHILDREN_SUCCESS = 'App/LOAD_CHILDREN_SUCCESS';
export const LOAD_CHILDREN_ERROR = 'App/LOAD_CHILDREN_ERROR';
export const DELETE_ITEMS = 'App/DELETE_ITEMS';
